# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-rails` gem.
# Please instead update this file by running `bin/tapioca gem rspec-rails`.

# The following code inspired and modified from Rails' `assert_response`:
#
#   https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/assertions/response.rb#L22-L38
#
# Thank you to all the Rails devs who did the heavy lifting on this!
#
# source://rspec-rails//lib/rspec/rails/feature_check.rb#1
module RSpec
  class << self
    # source://rspec-core/3.8.2/lib/rspec/core.rb#70
    def clear_examples; end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#85
    def configuration; end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#49
    def configuration=(_arg0); end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#97
    def configure; end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#167
    def const_missing(name); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def context(*args, &example_group_block); end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#122
    def current_example; end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#128
    def current_example=(example); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def describe(*args, &example_group_block); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def example_group(*args, &example_group_block); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def fcontext(*args, &example_group_block); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def fdescribe(*args, &example_group_block); end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#58
    def reset; end

    # source://rspec-core/3.8.2/lib/rspec/core/shared_example_group.rb#108
    def shared_context(name, *args, &block); end

    # source://rspec-core/3.8.2/lib/rspec/core/shared_example_group.rb#108
    def shared_examples(name, *args, &block); end

    # source://rspec-core/3.8.2/lib/rspec/core/shared_example_group.rb#108
    def shared_examples_for(name, *args, &block); end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#134
    def world; end

    # source://rspec-core/3.8.2/lib/rspec/core.rb#49
    def world=(_arg0); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def xcontext(*args, &example_group_block); end

    # source://rspec-core/3.8.2/lib/rspec/core/dsl.rb#42
    def xdescribe(*args, &example_group_block); end
  end
end

# source://rspec-core/3.8.2/lib/rspec/core.rb#160
RSpec::MODULES_TO_AUTOLOAD = T.let(T.unsafe(nil), Hash)

# Namespace for rspec-rails code.
#
# source://rspec-rails//lib/rspec/rails/feature_check.rb#2
module RSpec::Rails; end

# Disable some cops until https://github.com/bbatsov/rubocop/issues/1310
#
# @private
#
# source://rspec-rails//lib/rspec/rails/feature_check.rb#6
module RSpec::Rails::FeatureCheck
  private

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#11
  def can_check_pending_migrations?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#16
  def can_maintain_test_schema?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#46
  def has_1_9_hash_syntax?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#33
  def has_action_mailer?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#37
  def has_action_mailer_preview?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#41
  def has_action_mailer_show_preview?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#21
  def has_active_job?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#25
  def has_active_record?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#29
  def has_active_record_migration?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#50
  def has_file_fixture?; end

  # source://rspec-rails//lib/rspec/rails/feature_check.rb#54
  def type_metatag(type); end

  class << self
    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#11
    def can_check_pending_migrations?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#16
    def can_maintain_test_schema?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#46
    def has_1_9_hash_syntax?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#33
    def has_action_mailer?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#37
    def has_action_mailer_preview?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#41
    def has_action_mailer_show_preview?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#21
    def has_active_job?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#25
    def has_active_record?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#29
    def has_active_record_migration?; end

    # @return [Boolean]
    #
    # source://rspec-rails//lib/rspec/rails/feature_check.rb#50
    def has_file_fixture?; end

    # source://rspec-rails//lib/rspec/rails/feature_check.rb#54
    def type_metatag(type); end
  end
end

# Container module for Rails specific matchers.
#
# @api public
RSpec::Rails::Matchers = RSpec::Matchers

# Railtie to hook into Rails.
#
# source://rspec-rails//lib/rspec-rails.rb#9
class RSpec::Rails::Railtie < ::Rails::Railtie
  private

  # source://rspec-rails//lib/rspec-rails.rb#58
  def config_default_preview_path(options); end

  # @return [Boolean]
  #
  # source://rspec-rails//lib/rspec-rails.rb#46
  def config_preview_path?(options); end

  # source://rspec-rails//lib/rspec-rails.rb#40
  def setup_preview_path(app); end

  # @return [Boolean]
  #
  # source://rspec-rails//lib/rspec-rails.rb#63
  def supports_action_mailer_previews?(config); end
end

# source://rspec-core/3.8.2/lib/rspec/core/shared_context.rb#54
RSpec::SharedContext = RSpec::Core::SharedContext
