# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec_junit_formatter` gem.
# Please instead update this file by running `bin/tapioca gem rspec_junit_formatter`.

# Dumps rspec results as a JUnit XML file.
# Based on XML schema: http://windyroad.org/dl/Open%20Source/JUnit.xsd
#
# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#10
class RSpecJUnitFormatter < ::RSpec::Core::Formatters::BaseFormatter
  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#17
  def dump_summary(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#7
  def start(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#13
  def stop(notification); end

  private

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#58
  def classname_for(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#67
  def description_for(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#38
  def duration; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#63
  def duration_for(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#163
  def escape(text); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#26
  def example_count; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#50
  def example_group_file_path_for(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#42
  def examples; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#83
  def exception_for(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#34
  def failure_count; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#79
  def failure_for(notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#75
  def failure_message_for(example); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#71
  def failure_type_for(example); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#30
  def pending_count; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#46
  def result_of(notification); end

  # Returns the value of attribute started.
  #
  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#24
  def started; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#130
  def stderr_for(example_notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#126
  def stdout_for(example_notification); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#171
  def strip_diff_colors(string); end

  # rspec makes it really difficult to swap in configuration temporarily due to
  # the way it cascades defaults, command line arguments, and user
  # configuration. This method makes sure configuration gets swapped in
  # correctly, but also that the original state is definitely restored.
  #
  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#91
  def swap_rspec_configuration(key, value); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter/rspec3.rb#112
  def without_color(&block); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#14
  def xml_dump; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#66
  def xml_dump_example(example); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#36
  def xml_dump_examples; end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#55
  def xml_dump_failed(example); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#78
  def xml_dump_output(example); end

  # source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#49
  def xml_dump_pending(example); end
end

# Discouraged characters from https://www.w3.org/TR/xml/#charsets
# Plus special characters with well-known entity replacements
#
# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#125
RSpecJUnitFormatter::DISCOURAGED_REGEXP = T.let(T.unsafe(nil), Regexp)

# Translate well-known entities, or use generic unicode hex entity
#
# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#155
RSpecJUnitFormatter::DISCOURAGED_REPLACEMENTS = T.let(T.unsafe(nil), Hash)

# Inversion of character range from https://www.w3.org/TR/xml/#charsets
#
# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#93
RSpecJUnitFormatter::ILLEGAL_REGEXP = T.let(T.unsafe(nil), Regexp)

# Replace illegals with a Ruby-like escape
#
# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#105
RSpecJUnitFormatter::ILLEGAL_REPLACEMENT = T.let(T.unsafe(nil), Hash)

# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#168
RSpecJUnitFormatter::STRIP_DIFF_COLORS_BLOCK_REGEXP = T.let(T.unsafe(nil), Regexp)

# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#169
RSpecJUnitFormatter::STRIP_DIFF_COLORS_CODES_REGEXP = T.let(T.unsafe(nil), Regexp)

# source://rspec_junit_formatter//lib/rspec_junit_formatter.rb#185
RspecJunitFormatter = RSpecJUnitFormatter
