# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yt-auth/all/yt-auth.rbi
#
# yt-auth-0.3.1

module Yt
end
class Yt::Auth
  def access_token; end
  def access_token_was_refreshed; end
  def email; end
  def error_message_for(body); end
  def initialize(options = nil); end
  def profile; end
  def refresh_token; end
  def revoke; end
  def revoke_params; end
  def self.create(options = nil); end
  def self.find_by(options = nil); end
  def self.scope_for(scopes); end
  def self.url_for(options = nil); end
  def self.url_params(options); end
  def tokens; end
  def tokens_params; end
end
