# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yt-auth` gem.
# Please instead update this file by running `bin/tapioca gem yt-auth`.

# An object-oriented Ruby client for YouTube.
#
# @see http://www.rubydoc.info/gems/yt/
#
# source://yt-auth//lib/yt/auth.rb#7
module Yt; end

# Provides methods to authenticate a user with the Google OAuth flow.
#
# @see https://developers.google.com/accounts/docs/OAuth2
#
# source://yt-auth//lib/yt/auth.rb#10
class Yt::Auth
  # @option options
  # @option options
  # @option options
  # @option options
  # @param options [Hash] the options to initialize an instance of Yt::Auth.
  # @return [Auth] a new instance of Auth
  #
  # source://yt-auth//lib/yt/auth.rb#47
  def initialize(options = T.unsafe(nil)); end

  # @return [String] the access token of an authenticated Google account.
  #
  # source://yt-auth//lib/yt/auth.rb#64
  def access_token; end

  # Placeholder method that can be invoked after a refresh token is used
  # to generate a new access token. Applications can override this method,
  # for instance to store the new token in a database
  #
  # source://yt-auth//lib/yt/auth.rb#76
  def access_token_was_refreshed; end

  # @return [String] the email of an authenticated Google account.
  #
  # source://yt-auth//lib/yt/auth.rb#59
  def email; end

  # @return [String] the refresh token of an authenticated Google account.
  #
  # source://yt-auth//lib/yt/auth.rb#69
  def refresh_token; end

  # @return [Boolean] whether the authentication was revoked.
  #
  # source://yt-auth//lib/yt/auth.rb#54
  def revoke; end

  private

  # source://yt-auth//lib/yt/auth.rb#128
  def error_message_for(body); end

  # @return [Hash] the profile of an authenticated Google account.
  #
  # source://yt-auth//lib/yt/auth.rb#104
  def profile; end

  # source://yt-auth//lib/yt/auth.rb#120
  def revoke_params; end

  # @return [Hash] the tokens of an authenticated Google account.
  #
  # source://yt-auth//lib/yt/auth.rb#99
  def tokens; end

  # source://yt-auth//lib/yt/auth.rb#109
  def tokens_params; end

  class << self
    # @option options
    # @option options
    # @param options [Hash] the options to initialize an instance of Yt::Auth.
    #
    # source://yt-auth//lib/yt/auth.rb#16
    def create(options = T.unsafe(nil)); end

    # @option options
    # @param options [Hash] the options to initialize an instance of Yt::Auth.
    #
    # source://yt-auth//lib/yt/auth.rb#23
    def find_by(options = T.unsafe(nil)); end

    # source://yt-auth//lib/yt/auth.rb#92
    def scope_for(scopes); end

    # @option options
    # @option options
    # @option options
    # @param options [Hash] the options to initialize an instance of Yt::Auth.
    # @return [String] the URL where to authenticate with a Google account.
    #
    # source://yt-auth//lib/yt/auth.rb#35
    def url_for(options = T.unsafe(nil)); end

    # source://yt-auth//lib/yt/auth.rb#81
    def url_params(options); end
  end
end
