# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yt-support/all/yt-support.rbi
#
# yt-support-0.1.3

module Yt
  extend Yt::Config
end
class Yt::Configuration
  def access_token; end
  def access_token=(arg0); end
  def api_key; end
  def api_key=(arg0); end
  def client_id; end
  def client_id=(arg0); end
  def client_secret; end
  def client_secret=(arg0); end
  def debugging?; end
  def developing?; end
  def initialize; end
  def log_level; end
  def log_level=(arg0); end
  def refresh_token; end
  def refresh_token=(arg0); end
end
module Yt::Config
  def configuration; end
  def configure; end
end
class Yt::ConnectionError < StandardError
end
class Yt::HTTPError < StandardError
  def initialize(msg, response:); end
  def response; end
end
class Yt::HTTPRequest
  def as_curl; end
  def camelize(part); end
  def error_message; end
  def http_request; end
  def initialize(options = nil); end
  def parse_response!; end
  def query; end
  def response; end
  def run; end
  def server_errors; end
  def set_request_body!(request); end
  def set_request_headers!(request); end
  def uri; end
end
