AllCops:
  TargetRubyVersion: "2.7.2"
  Exclude:
    - db/schema.rb
    - config/**/*
    - bin/*
    - log/**/*
    - tmp/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
